### ISSUE TITLE
A11y_AzureToolsStorageExplorer_ConfigureSoftDeletePolicy_keyboard: Loss of keyboard focus is found after "Cancel" button.

### ISSUE THREAD

**Issue by vinodbk197** [microsoft/AzureStorageExplorer#1963]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags: #A11y_AzureToolsStorageExplorer; #A11yMAS; #A11YTCS; #DesktopApp; #MAS2.4.7; #Keyboard; #Mac;

**Environment Details:**
Application Name: Azure Tools Storage Explorer
Application Version: 1.10.0
MAC Version 10.14.6 Beta(18G29g)

**Repro Steps:**
 1. Launch Storage Explorer.
 2. Navigate to "Open Connect dialog" pane and Sign in to Azure.
 3. Go to "Manage Accounts" pane and Select the subscriptions you will use. Once selected, click 
     on "Apply" button.
4. Navigate to "Blob Containers" of the selected subscription, right click and Select "Configure 
   Soft Delete Policy" and hit enter.
5. Start Navigating on the screen using TAB key.
6. Verify Keyboard focus is lost after "Cancel" button.

**​Actual:​**
Loss of keyboard focus is found after "Cancel" button.
Keyboard focus stuck on "Cancel" button by using "Tab" and "Shift+Tab" key, focus not moves and it remains on "Cancel" button. 

**Same issue is observed throughout the application for all the dialog screens.

**Expected:**
Keyboard focus should not be lost after "Cancel" button. Instead focus when it is Tab Keyboard focus should shift to "What is Soft Delete?" link.
Keyboard focus should not be stuck on "Cancel" button by using "Tab" and "Shift+Tab" key focus should moves to other controls present on the screen.

**User Impact:**
If keyboard focus is lost after cancel button they keyboard only users face difficulty to know where the keyboard focus is on the screen.

**Recommendation**:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**MAS Reference**:
https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={3b98b04f-4fab-4d3e-81af-a0906a34849c}

**Attachment for Reference:**
[1963_A11y_AzureToolsStorageExplorer_ConfigureSoftDeletePolicy_keyboard.pptx](https://github.com/microsoft/AzureStorageExplorer/files/3669468/1963_A11y_AzureToolsStorageExplorer_ConfigureSoftDeletePolicy_keyboard.pptx)
[1963_ConfigureCORSSettings.pptx](https://github.com/microsoft/AzureStorageExplorer/files/3670295/1963_ConfigureCORSSettings.pptx)

**Comment by MRayermannMSFT** [comment]
Figure out how to resolve as "in vpat"

**Comment by MRayermannMSFT** [comment]
Good news! This bug was fixed in electron 5.0.0. If we can upgrade to that, then no more extra tab stops at the ends of Windows. :)

**Comment by Alexandria-R** [comment]
Approved for exclusion as low impact.

**Comment by vinodbk197** [comment]
@MRayermannMSFT 
Verified this issue on: Application Name: Azure Tools Storage Explorer
Application Version: 1.12.0
As part of core scenario test execution, This issue (Keyboard focus is lost after the "cancel" button) is still reproduces for the below scenario.

1.Connect to Azure Storage
2.Delete Popup
3.Upload Files
4.Upload Folder
5.Update Access Tier
6.Clone with New Name Blob
7.Break Lease Popup
8.Rename Blob Container
