### ISSUE TITLE
The access tiers are not localized for one GPV2 storage account 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2211]
**Storage Explorer Version:** 1.11.0
**Build:** [20191105.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3213388)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Language:** Czech/ German/ Spanish/ French/ Hungarian/ Italian/ Japanese/ Korean/ Dutch/ Polish/ Portuguese (Brazil)/ Portuguese (Portugal)/ Russian/ Swedish/ Turkish/ Chinese (Simplified) / Chinese (Traditional)
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Chinese (simplified)' -> Restart Storage Explorer.
3. Select one GPV2 storage account -> Right click it -> Click 'Set Default Access Tier...'.
4. Check the dialog.

**Expect Experience:**
The access tiers are localized.

**Actual Experience:**
The access tiers are not localized.
![image](https://user-images.githubusercontent.com/54055206/68196268-503fb900-fff3-11e9-84bd-c950a5303f62.png)

**More Info:**
1. Verified this issue in Chinese(zh-CN)/ Chinese(zh-TW)/ Japanese/ Korean.
2. This issue also reproduces for one **regular blob.**
![image](https://user-images.githubusercontent.com/54055206/68196777-0acfbb80-fff4-11e9-93ec-6f7ed7017764.png)

3. This issue **doesn't** reproduce for one **ADLS Gen2 blob.**
![image](https://user-images.githubusercontent.com/54055206/68196835-1f13b880-fff4-11e9-9cdd-7d1e57c3644c.png)

**Comment by lukaschal** [comment]
Localized at 10/20/19.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer?_a=annotate&path=%2Floc%2Floc%2Fzh-Hans%2Fsrc%2Fcomponents%2Fse-blob-extension%2Fresources%2FBlobActions.json.lcl&version=GBmaster

**Comment by v-limu** [comment]
This issue also reproduces in **Japanese**.
![image](https://user-images.githubusercontent.com/54055206/71237864-9c458380-233d-11ea-8b58-bdf0cc7ee760.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into master.

**Comment by v-limu** [comment]
Verified this issue on build [20200216.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3477731). 'Archive' is not translated for one regular blob. So we reopen it.
![image](https://user-images.githubusercontent.com/54055206/74619635-2741cf00-5171-11ea-9a77-98ed287b66e5.png)

**Comment by MRayermannMSFT** [comment]
Ok. I'll need to check back later once that one is translated.

**Comment by MRayermannMSFT** [comment]
Looks like the strings are loc'd now. Closing.

**Comment by v-xianya** [comment]
Verified on build [20200226.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3502854).
This issue still reproduces in Swedish. So we open it.
![image](https://user-images.githubusercontent.com/41351993/75310293-7df48a80-588e-11ea-9ce8-3673b06b08b0.png)

**Comment by MRayermannMSFT** [comment]
@lukaschal are those translations correct for Swedish? I'm looking at se-blob-extension/resources/sv/BlobActions.json

**Comment by lukaschal** [comment]
@MRayermannMSFT Verifying with linguist.

**Comment by MRayermannMSFT** [comment]
@lukaschal any word from the linguist?

**Comment by lukaschal** [comment]
@MRayermannMSFT Localized now.

SRC: Hot
New TGT: Frekvent

SRC: Cool
New TGT: Lågfrekvent

**Comment by MRayermannMSFT** [comment]
Cool Thanks.

**Comment by MRayermannMSFT** [comment]
Verified.
