### ISSUE TITLE
Issue while syncing local storage explorer with blob storage

### ISSUE THREAD

**Issue by jain6968** [microsoft/AzureStorageExplorer#3160]
**Storage Explorer Version**: 2.1.0
**Build Number**: 
**Platform/OS**: Windows 10
**Architecture**: X64
**Regression From**:  Not tested earlier

## Bug Description ##
Unable to retrieve child resources.

Details:
["RestError:request to https://localvideostor.blob.core.windows.net/?include=metadata&comp=list failed, reason: getaddrinfo ENOTFOUND localvideostor.blob.core.windows.net"]

## Expected Experience ##
On uploading any file in local storage explorer, the files/ videos should auto sync in Cloud blob storage

**Comment by jinglouMSFT** [comment]
hmm...this is confusing.  What exactly is the product you are using?  We don't have a Storage Explorer version 2.1.0.  The latest version we have released is v1.14.0.

**Comment by jain6968** [comment]
Yeah, sorry I am using 1.14.0 latest one. I mentioned the python lib version 2.1.0, so plz ignore that.

**Comment by jain6968** [comment]
To add  further details, I am using IOTedge deployment template for deploying blob storage on edge service 
Below is deployment template for IOT edge,
{
  "modulesContent": {
    "$edgeAgent": {
      "properties.desired": {
        "modules": {
          "camera-capture": {
            "settings": {
              "image": "cvacr2020.azurecr.io/cameracapture:0.2.8-test-amd64",
              "createOptions": "{\"HostConfig\":{\"PortBindings\":{\"5012/tcp\":[{\"HostPort\":\"5012\"}]},\"Binds\":[\"/dev/video0:/dev/video0\"]}}"
            },
            "type": "docker",
            "version": "1.0",
            "env": {
              "PRIVATE_IP_VM": {
                "value": "10.0.0.4"
              },
              "LOCAL_STORAGE_KEY": {
                "value": "UsldhPEq390NNvUj2JRk0K0vBrmkS88dgAFuEwAuXHjCP6uXldU0AN12pbT/1nARiVaGgu3vTI9zsoJ2gm3/8Q=="
              },
              "LOCAL_STORAGE_NAME": {
                "value": "localvideostor"
              },
              "VIDEO_PATH": {
                "value": "./traingraffiti.mp4"
              },
              "IMAGE_PROCESSING_ENDPOINT": {
                "value": "http://image-classifier-service:80/image"
              },
              "VERBOSE": {
                "value": "True"
              },
              "RESIZE_WIDTH": {
                "value": "256"
              },
              "RESIZE_HEIGHT": {
                "value": "256"
              },
              "SHOW_VIDEO": {
                "value": "True"
              }
            },
            "status": "running",
            "restartPolicy": "always"
          },
          "image-classifier-service": {
            "settings": {
              "image": "cvacr2020.azurecr.io/imageclassifierservice:0.2.5-amd64",
              "createOptions": ""
            },
            "type": "docker",
            "version": "1.0",
            "status": "running",
            "restartPolicy": "always"
          },
          "azureblobstorageoniotedge": {
            "settings": {
              "image": "mcr.microsoft.com/azure-blob-storage:latest",
              "createOptions": "{\"Env\":[\"LOCAL_STORAGE_ACCOUNT_NAME=localvideostor\",\"LOCAL_STORAGE_ACCOUNT_KEY=UsldhPEq390NNvUj2JRk0K0vBrmkS88dgAFuEwAuXHjCP6uXldU0AN12pbT/1nARiVaGgu3vTI9zsoJ2gm3/8Q==\"],\"HostConfig\":{\"Binds\":[\"/srv/containerdatalocal:/blobroot\"],\"PortBindings\":{\"11002/tcp\":[{\"HostPort\":\"11002\"}]}}}"
            },
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "version": "1.0"
          }
        },
        "runtime": {
          "settings": {
            "minDockerVersion": "v1.25",
            "registryCredentials": {
              "registryName": {
                "address": "cvacr2020.azurecr.io",
                "password": "T76HkhRUYvyt/tN=8zmw4n0LcxJV6g=J",
                "username": "cvacr2020"
              }
            }
          },
          "type": "docker"
        },
        "schemaVersion": "1.0",
        "systemModules": {
          "edgeAgent": {
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.0",
              "createOptions": ""
            },
            "type": "docker"
          },
          "edgeHub": {
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.0",
              "createOptions": ""
            },
            "type": "docker",
            "status": "running",
            "restartPolicy": "always"
          }
        }
      }
    },
    "$edgeHub": {
      "properties.desired": {
        "routes": {
          "CameraCaptureToIoTHub": "FROM /messages/modules/camera-capture/outputs/output1 INTO $upstream"
        },
        "schemaVersion": "1.0",
        "storeAndForwardConfiguration": {
          "timeToLiveSecs": 7200
        }
      }
    },
    "camera-capture": {
      "properties.desired": {}
    },
    "image-classifier-service": {
      "properties.desired": {}
    },
    "azureblobstorageoniotedge": {
      "properties.desired": {
        "deviceToCloudUploadProperties": {
          "uploadOn": true,
          "uploadOrder": "OldestFirst",
          "cloudStorageConnectionString": "DefaultEndpointsProtocol=https;AccountName=cvstorage2020;AccountKey=FiPUJgzf02/YsHE/A24YPT8pfxJj+BjkouoAUm8oLkCcMeRx7T6Mp7reVB5ONaKfMWhjNbwsu9jJ+QNurBzTlw==;EndpointSuffix=core.windows.net",
          "storageContainersForUpload": {
            "localvideostor": {
              "target": "videoblob"
            }
          },
          "deleteAfterUpload": true
        }
      }
    }
  }
}

**Comment by MRayermannMSFT** [comment]
@jain6968 are you still having problems? If so, I can try to get someone from the IoT team here to help you. Also, please note that you'll need to use Storage Explorer 1.14 with IoT for now. The IoT software is a bit behind on API versions, and newer versions of Storage Explorer have moved to later API versions.

**Comment by cclague** [comment]
I'm still having an issue with this too - are you able to point me to where I can get storage explorer 1.14 for Mac too to help diagnose, thanks

**Comment by MRayermannMSFT** [comment]
Most old versions can be found at https://github.com/microsoft/AzureStorageExplorer/releases

**Comment by MRayermannMSFT** [comment]
Closing due to lack of followup. If you're having any issues still, please open a new issue.
