### ISSUE TITLE
Keep a consistent localized 'URL' for the four services in the properties panel

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3547]
**Storage Explorer Version:** 1.15.1
**Build**: 20200904.2
**Branch**: main
**Platform/OS:** Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Language**:  Spanish/ Czech/ Swedish
**Regression From:** Not a regression

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Open 'Settings' -> Application (Regional Settings) -> Select 'Español' -> Restart Storage Explorer.
3. Expand one storage account -> Click one queue -> Check the localized 'URL' in the properties panel.
4. Check the localized 'URL' for other three services.

**Expect Experience:**
Keep a consistent localized 'URL' for the four services in the properties panel.

**Actual Experience:**
Show inconsistent localized 'URL' for the four services in the properties panel.  
![image](https://user-images.githubusercontent.com/54055206/92451166-fa2d3a80-f1ee-11ea-897b-4f0b2fe835ad.png)

**More Info:**
The screenshot in ENU:
![image](https://user-images.githubusercontent.com/54055206/92451264-14671880-f1ef-11ea-9928-59ce0851d84f.png)

**Comment by craxal** [comment]
@cristianosuzuki77 Can you look into this? Is it common for "URL" to have different translations?

**Comment by cristianosuzuki77** [comment]
Feedback incorporated. Tracking here: https://ceapex.visualstudio.com/CEINTL/_queries/edit/340472/?triage=true

**Comment by cristianosuzuki77** [comment]
@craxal this is resolved and the fixes were checked-in.

**Comment by v-limu** [comment]
Hi @cristianosuzuki77 
Verified on the new build 20201204.5. This issue fixed in language Spanish. But it is still reproduces in language Czech/ Swedish. 

![image](https://user-images.githubusercontent.com/54055206/101134226-0174b080-3645-11eb-8af9-139579378e4b.png)
![image](https://user-images.githubusercontent.com/54055206/101134516-7647ea80-3645-11eb-80e8-cf4e0bc2c133.png)

**Comment by cristianosuzuki77** [comment]
Hello @v-limu 
PR lego/hb_2266_20201201181209119  with this fix was done on 12/1 into main (item ID LabelPropertyUrl in Queues.json).
Could you check the repo or build and confirm the case? Could you let me know if these two instances are from another location?

**Comment by v-limu** [comment]
Hi @cristianosuzuki77  

We verified on **new build 20201206.2** and **the build 20201201.4 which merged** 'PR lego/hb_2266_20201201181209119'. This issue still reproduces on Czech/ Swedish.

**Comment by cristianosuzuki77** [comment]
@craxal could you verify if the PR above was built?

**Comment by cristianosuzuki77** [comment]
@v-limu Could you help and share the string ID of the string you are still seeing with the wrong translation?

**Comment by v-limu** [comment]
Hi @cristianosuzuki77 😊 ok. The string of the the wrong translation for 'URL' shows below:

In Czech:  Adresa URL
![image](https://user-images.githubusercontent.com/54055206/101431016-18671b80-3941-11eb-8d19-1eacbdf4e8a6.png)

In Swedish:  Webbadress
![image](https://user-images.githubusercontent.com/54055206/101431175-5c5a2080-3941-11eb-8942-80b976c8f981.png)
