### ISSUE TITLE
Quick Access table node doesn't display as broken when removing the Azure account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5069]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211016.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6
**Architecture**: ia32\x64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Select one file share -> Add it to quick access.
3. Go to 'ACCOUNT MANAGEMENT' panel -> Remove the account.
4. Go to 'EXPLORER' panel -> Check whether the QA file share displays as broken.

## Expected Experience ##
The QA file share displays as broken.

## Actual Experience ##
The QA file share displays well.

## Additional Context ##
1. This issue doesn't reproduce for blob containers.
2. Related issue: [3176](https://github.com/microsoft/AzureStorageExplorer/issues/3176).

**Comment by MRayermannMSFT** [comment]
@v-xianya I have added the expected behavior for file shares. Can you please confirm that you are now seeing that behavior?

**Comment by v-xianya** [comment]
@MRayermannMSFT This issue has been fixed for file shares.

**Comment by MRayermannMSFT** [comment]
Awesome, thank you for confirming! I'm going to edit this title and move to 1.23 where we can do table and queue part of the work.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220212.2. Fixed.

**Comment by craxal** [comment]
Still occurring, because I didn't show table nodes as broken if other credentials were present.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220214.5. Fixed.
