### ISSUE TITLE
Only the selected columns display in the 'Column Options' dialog

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5955]
**Storage Explorer Version:** 1.25.0-dev
**Build Number:** 20220721.9
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Previous release (1.24.3)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Click 'Column Options'.
3. Uncheck 'RowKey' column -> Click 'OK'.
4. Click 'Column Options' -> Check whether all columns display in the dialog.

## Expected Experience ##
All columns display.
![image](https://user-images.githubusercontent.com/87792676/180174912-a3f91dd3-f467-4bc0-95af-010737516bc9.png)

## Actual Experience ##
Only the selected column displays.
![image](https://user-images.githubusercontent.com/87792676/180174486-200ee25d-7460-4b7e-8254-19bda671766c.png)

**Comment by craxal** [comment]
This was due to some more discrepancies between how the table component and the column manager track columns. When updating the displayed columns, the column manager filters out the hidden columns. This gets passed to the component such that the column is entirely absent. Since the fix for #5944, this missing column translates to the dialog.

This is fixed by not filtering out hidden columns and simply adding a `visible` property to the column setting interface used with the component.

**Comment by v-kellyluo** [comment]
This issue still reproduces on the build main/20220725.1, so we are going to reopen it.

**Comment by craxal** [comment]
The fix must have got gobbled up in a bad merge with all the other changes we were trying to get in.

**Comment by v-kellyluo** [comment]
Verified this issue on the build main/20220727.2. Fixed.
