### ISSUE TITLE
It jumps back to page 1 and the editor shows blank if select the page from next batch then clicking refresh for file shares/tables

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8588]
### Storage Explorer Version

1.39.0-dev (105)

### Regression From

1.38.0

### Architecture

x64

### Storage Explorer Build Number

20250427.1

### Platform

All

### OS Version

Windows 11 arm64/Windows11 x64/Linux Ubuntu 22.04/MacOS Sequoia 15.4.1(Apple M1 Pro)

### Bug Description

It jumps back to page 1 and the editor shows blank if select the page from next batch then clicking refresh for file shares/tables.

For file share, this issue regression from 1.38.0.
For tables, this issue regression from 1.36.0.

### Steps to Reproduce

1. Expand one storage account -> File Shares.
2. Create a file share -> Upload 10000 files.
3. Click 'Load more' to load all files.
4. Select page 100 -> Click 'Refresh'.
5. Check whether it jumps back to the page 50 and the editor shows well.

### Actual Experience

1. It jumps back to the page 1.
2. The editor is blank.
![Image](https://github.com/user-attachments/assets/9213ccb8-cd12-4508-b76e-94f25189ec17)

### Expected Experience

1. It jumps back to the page 50.
2. The editor shows well.

![Image](https://github.com/user-attachments/assets/0b2d231d-8e1c-4bcf-8680-36d1043b63fa)

### Additional Context

Here is the screenshot for tables:
![Image](https://github.com/user-attachments/assets/d0983bf2-621c-4ad6-8b3c-2a0906a57309)

**Comment by craxal** [comment]
Surprised we haven't caught this earlier. Most paging properties are calculated. The paging hook only clamps the page index when the page index is being updated. It does not take into account external changes (such as the number of items shrinking), which throws off calculations. This is easily fixed by clamping the page index to the total number of pages.

**Comment by v-xianya** [comment]
Hi @craxal Verified this issue on the main build 20250509.2. Fixed on file share.
 **Still reproduce for tables.**
