### ISSUE TITLE
Cosmos DB documents no longer visible

### ISSUE THREAD

**Issue by critchie** [Microsoft/AzureStorageExplorer#971]
**Storage Explorer Version**: 1.6.0
**Platform/OS**: Windows
**Architecture**:
**Regression From**: Was this working in a previous version? Yes. 1.5.0

**Bug description**
After installing 1.6.0, when I navigate to my documents and click, the Documents tab is empty.

**Steps to Reproduce**
List the minimal steps clearly and concisely to reproduce the behavior:
1. Open Storage Explorer
2. Expand the Pay-As-You-Go
3. Expand Cosmos DB Accounts (Preview)
4. Expand my database account
5. Expand my database
6. Expand my collection
7. Click on Documents

**Expected Experience**
I expected a tab to open in the right pane with my documents visible.

**Actual Experience**
Documents tab is opened but there are no documents.

**Additional Context**
I figure I'm missing a release note somewhere on this.  I tried the --disable-gpu but that didn't help.

**Comment by scholtes** [comment]
I had the same problem updating to `1.6.0` 
Screenshot: 
![image](https://user-images.githubusercontent.com/3686667/49594855-5c7f4a00-f93c-11e8-9e81-3e0d140e1b53.png)
Green is redacted names, everything else in the screenshot is how it appears -- notice the blank black space in the open documents tab. 

Some other notes: 

- Bug exists with other color themes 
- Bug exists when accessing document when using quck access and when not using quick access  
- After the 1.6.0 update I had to re-authenticate with Azure within Storage Explorer, and then "Remove from Quick Access" and re-"Add to Quick Access".  This was not required following previous updates.

**Comment by jkonecki** [comment]
The JavaScript error which I believe is causing the issue:

```
No attribute loader for: partitionKeyValue error @ Debug.js:39 (anonymous) @ BindingHandler.js:27 tryCatch @ -internal.js:195 invokeCallback @ -internal.js:210 publish @ -internal.js:178 publishRejection @ -internal.js:120 flush @ asap.js:98 characterData (async) (anonymous) @ asap.js:70 asap @ asap.js:20 (anonymous) @ then.js:23 then @ then.js:26 NodeAttributeResolver.resolveAttributes @ NodeAttributeResolver.js:44 BindingHandler._evaluateAttribute @ BindingHandler.js:65 BindingHandler.updateValue @ BindingHandler.js:21 BindingHandlerSet.updateBoundArgument @ BindingHandlerSet.js:33 BindingHandlerSet.resolveArguments @ BindingHandlerSet.js:22 ActionViewModel.resolveArguments @ ActionViewModel.js:19 (anonymous) @ NodeViewModel.js:354 step @ CloudExplorerViewModel.js:34 (anonymous) @ CloudExplorerViewModel.js:15 (anonymous) @ CloudExplorerViewModel.js:9 __awaiter @ CloudExplorerViewModel.js:5 NodeViewModel.executeAction @ NodeViewModel.js:347 defaultAction @ NodeViewModel.js:552 NodeViewModel.executeDefaultAction @ NodeViewModel.js:560 NodeViewModel.handleClick @ NodeViewModel.js:587 (anonymous) @ knockout.js:79 dispatch @ jquery.js:4430 elemData.handle @ jquery.js:4116
```

**Comment by ziyel** [comment]
Thanks for feeback.
We are preparing a hotfix for this.

**Comment by chrisparkeronline** [comment]
This is happening for me also. Forced to use the document explorer in Azure portal now until the hotfix!

**Comment by br14** [comment]
I'm experiencing the same issue. Tried the suggested fix "./StorageExplorer.exe --disable-gpu" but it made no difference.

**Comment by AntonioJDios** [comment]
When will be ready the hot fix patch??

**Comment by ziyel** [comment]
We will fix this in version `1.6.1` which is planning release in 17th Dec.

**Comment by rasmuschristensen** [comment]
Same issue on mac, blank screen when clicking documents. The "hack" from @darrengillis made a temporary fix.

**Comment by MRayermannMSFT** [comment]
For anyone facing this issue, we're shipping a hotfix to fix this regression. Until then you can either do the hack as others have suggested, or if you'd like to preview the hotfix simply go to the "Help" menu on Windows and Linux/app menu on macOS ->" Opt in to Insider Builds" We'll still doing some final testing and a few other fixes, but we wanted to at least let people who needed the fixes we have done so far, have them. Thanks!

**Comment by richmwatts** [comment]
I am still experiencing this issue in 1.6.2, specifically seeing the js error that @jkonecki referenced in his comment. I have actually lost a lot of time on this thinking it was a setup issue.

Seeing the comment RE the line of code that is parsing subscription metadata. My azure account is connected to multiple Azure subscriptions as it is my company account - just thought I would add that piece of information incase it turns on any lightbulbs.

**Comment by richmwatts** [comment]
After deciding to dig into this a little more I think I have found the source of the issue. 

This issue only effects Cosmos DB's created with the MongoDB API, as ones created with the SQL API allow Azure Storage Explorer to function correctly.

Inside of AzureDocumentDBActions.js there is a hard-coded Array of **_actions_** which appear to require a one-to-one mapping to the **_resourceType_** - it appears that the code is expecting this _**resourceType**_ to be **_MongoDB_** when it is actually **_Azure Cosmos DB for MongoDB API_** see screenshot:

![incorrect-resourcetype](https://user-images.githubusercontent.com/3800653/51809691-c6600400-229a-11e9-9ba9-1a0bab7d72b2.png)

I added some code to stop this and managed to get Storage Explorer to correctly show my collections. However, I then also noticed that the correct menu was not being shown when right clicking on my database to create a collection. See screenshot:

![incorrect-menu](https://user-images.githubusercontent.com/3800653/51809870-463a9e00-229c-11e9-88cb-9df164a15231.png)

As you can see the _**Create Collection**_ option is missing.

I believe I have tracked this issue down to the expression builder used to toggle the visibility of the menu option in question. See screenshot:

![permission-issue](https://user-images.githubusercontent.com/3800653/51809963-bcd79b80-229c-11e9-9a18-ae54338321b8.png)

I believe this is also likely related to the original issue (an incorrect **_resourceType_**) as modifying the expression to expect the string **_Azure Cosmos DB for MongoDB API_** will correctly render the **_Create Collection_** menu option.

I also noticed that when creating a Cosmos DB account in the Azure Portal the API dropdown has this string as the Mongo option. See screenshot:

![portal-creation](https://user-images.githubusercontent.com/3800653/51810276-cfeb6b00-229e-11e9-8acc-ac449c4513c7.png)

Hope this helps.

Rich

**Comment by chrisparkeronline** [comment]
Great investigation Rich!

**Comment by rasmuschristensen** [comment]
awesome @richmwatts . I'm using the SQLAPI and after the hotfix it works for me again.

**Comment by craxal** [comment]
@richmwatts, great work! I don't suppose you'd be interested in contributing if this project were open sourced (#138)?

**Comment by richmwatts** [comment]
No problem at all guys. Enjoyed it, love problem solving 👍 As for wanting to contribute, absolutely!

**Comment by MRayermannMSFT** [comment]
Fix was merged a few days ago for 1.7.0.

**Comment by akshaybabloo** [comment]
I still can't seem to see the documents

**Comment by craxal** [comment]
@akshaybabloo If you are still having problems, please open a new issue.

**Comment by joedevgee** [comment]
Still not able to see documents with Mongo protocol. I don't think it matters but here is my system info
```
Version: 1.13.0
AzCopy Version: 10.4.2

Platform: macOS
Architecture: x64 
Build Number: 20200430.5 
Commit: c82c50eca 
Support ID: 55ae0cb1-287f-89f2-cebf-7cadf440b255 

```

**Comment by craxal** [comment]
@joedevgee Can you open a new issue, please? This issue has been closed for a while.

**Comment by jsutes** [comment]
Here's the link to the new issue for MongoDB: https://github.com/microsoft/AzureStorageExplorer/issues/2584
