### ISSUE TITLE
Unable to view CosmosDB documents in 1.6.0

### ISSUE THREAD

**Issue by jkonecki** [Microsoft/AzureStorageExplorer#972]
**Storage Explorer Version**: 1.6.0
**Platform/OS**: Windows
**Architecture**: 64bit
**Regression From**: 1.5.0

**Bug description**

When opening a tab or query tab for CosmosDB instance hosted in Azure the following error is reported and the tab remains blank. Browsing local emulator works fine.
```

No attribute loader for: partitionKeyValue
error @ Debug.js:39
(anonymous) @ BindingHandler.js:27
tryCatch @ -internal.js:195
invokeCallback @ -internal.js:210
publish @ -internal.js:178
publishRejection @ -internal.js:120
flush @ asap.js:98
characterData (async)
(anonymous) @ asap.js:70
asap @ asap.js:20
(anonymous) @ then.js:23
then @ then.js:26
NodeAttributeResolver.resolveAttributes @ NodeAttributeResolver.js:44
BindingHandler._evaluateAttribute @ BindingHandler.js:65
BindingHandler.updateValue @ BindingHandler.js:21
BindingHandlerSet.updateBoundArgument @ BindingHandlerSet.js:33
BindingHandlerSet.resolveArguments @ BindingHandlerSet.js:22
ActionViewModel.resolveArguments @ ActionViewModel.js:19
(anonymous) @ NodeViewModel.js:354
step @ CloudExplorerViewModel.js:34
(anonymous) @ CloudExplorerViewModel.js:15
(anonymous) @ CloudExplorerViewModel.js:9
__awaiter @ CloudExplorerViewModel.js:5
NodeViewModel.executeAction @ NodeViewModel.js:347
defaultAction @ NodeViewModel.js:552
NodeViewModel.executeDefaultAction @ NodeViewModel.js:560
NodeViewModel.handleClick @ NodeViewModel.js:587
(anonymous) @ knockout.js:79
dispatch @ jquery.js:4430
elemData.handle @ jquery.js:4116
```

**Steps to Reproduce**
List the minimal steps clearly and concisely to reproduce the behavior:
1. Open a new tab for CosmosDB instance (not local emualtor) 

**Expected Experience**
Ability to view and query documents

**Actual Experience**
Tab is blank, without buttons.

**Comment by critchie** [comment]
Similar issue: #971

Error detail looks helpful.  Our collections have been around a while, they are fixed at 10GB and I don't think they were created with a Partition Key.

**Comment by craxal** [comment]
Duplicate of #971. Please continue discussion there if needed.

**Comment by MRayermannMSFT** [comment]
For anyone facing this issue, we're shipping a hotfix to fix this regression. Until then, if you'd like to preview the hotfix simply go to the "Help" menu on Windows and Linux/app menu on macOS ->" Opt in to Insider Builds" We'll still doing some final testing and a few other fixes, but we wanted to at least let people who needed the fixes we have done so far, have them. Thanks!

**Comment by AndresHurtadoRMT** [comment]
I still have the same problem on Azure Portal, Storage Explorer Version 1.7.0 insider builds and VS code Azure-Cosmos DB plugin.

**Comment by jinglouMSFT** [comment]
@djlan Any idea?  Thanks.
